### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by JoeyMBrown** [JoeyMBrown/Simple-Calculator#1]
- [x]  Allow calculator to compute decimals.
- [ ] Allow calculator to compute negatives.
- [x] Allow calculator to compute more than 2 inputs at a time.
- [ ] Order of operations - Toughest Challenge
- [ ] Update look of calculator.

**Comment by dannyrb** [comment]
- [ ] Checkboxes O_o
- [x] Hi Joey
- [ ] Also, these could be in your `readme`

**Comment by JoeyMBrown** [comment]
Oooo thanks.  Didn't know I could create check boxes ha.
